### ISSUE TITLE
Mystic t-sne last step

### ISSUE THREAD

**Issue by RaghdaAB** [MathOnco/Mistic#1]
Hello,
Hope all is well I tried several time to do the steps for the mystic I keep getting an error for the the r-requirement.txt  and also for the last step I get the website but it is totally empty.

**Comment by sandhya212** [comment]
Hi @RaghdaAB, thank you for your interest in Mistic!
Could you please give details of the exact error you get when you run 
a). r-requirement.txt and 
b) error/display message in the console when you run the last step

**Comment by Raghda1** [comment]
Hello this is the error I get @sandhya212  ERROR: Could not find a version that satisfies the requirement PhenoGraph==1.5.2 (from versions: 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7)
ERROR: No matching distribution found for PhenoGraph==1.5.2
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/Users/raghda/pythonProject_mistic/bin/python -m pip install --upgrade pip' command.

**Comment by sandhya212** [comment]
Hi @RaghdaAB, the requirements.txt file captures the Python package dependencies. There are also many interdependencies that exist depending on the version of Python and OS that you have already installed. 

You can try two options: 
1. I have updated the requirements.txt for Phenograph. Note how I changed the version from 1.5.2 to 1.5.3. (You can do this for any other package that issues a version mismatch). 
2. You can use the same requirements.txt you have but just delete the '==1.5.2' after Phenograph. 

After 1 or 2, continue with issuing the bokeh command as discussed in the Readme.

Please update me how either of these options work. 
Thanks again!

**Comment by Raghda1** [comment]
@sandhya212 Thank you but I still get the same error.   ERROR: Could not find a version that satisfies the requirement PhenoGraph==1.5.2 (from versions: 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7)
ERROR: No matching distribution found for PhenoGraph==1.5.2
We are a group of 3 stuck at this may we schedule a zoom meeting with you?

**Comment by sandhya212** [comment]
Ok, we can walk this through. Could you please DM me?
